unbind r
bind r source-file ~/.tmux.conf

set -g base-index 1
setw -g pane-base-index 1
set-option -g status-keys vi
set-option -g bell-action any
set-option -g visual-bell on

setw -g mode-keys vi
setw -g monitor-activity on

set-option -g status-justify left
set-option -g status-bg black
set-option -g status-fg white
set-option -g status-left-length 40

set -g history-limit 50000

# keybindings
set -g prefix C-a
bind-key prefix h select-pane -L
bind-key prefix j select-pane -D
bind-key prefix k select-pane -U
bind-key prefix l select-pane -R

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'lawabidingcactus/tmux-gruvbox-truecolor'
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'
