unbind r
bind r source-file ~/.tmux.conf

set-option -g status-keys vi
set-option -g bell-action any
set-option -g visual-bell on

setw -g mode-keys vi
setw -g monitor-activity on

set-option -g status-justify left
set-option -g status-bg black
set-option -g status-fg white
set-option -g status-left-length 40

set -g history-limit 10000

# keybindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind r source-file ~/.tmux.conf

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'lawabidingcactus/tmux-gruvbox-truecolor'
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'
