set-option -g status-keys vi
set-option -g bell-action any
set-option -g visual-bell on

setw -g mode-keys vi
setw -g monitor-activity on

set-option -g status-justify left
set-option -g status-bg black
set-option -g status-fg white
set-option -g status-left-length 40

set -g history-limit 4096

bind r source-file ~/.tmux.conf

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'

# plugins configuration
set -g @themepack 'powerline/block/blue'

run -b '~/.tmux/plugins/tpm/tpm'
