;;; jbeans-theme.el --- Jbeans theme for GNU Emacs 24 (deftheme)

;; Author: Adam Olsen <arolsen@gmail.com>
;; Version: 1.0
;; Based On: ujelly by Mark Tran
;; "What do you mean, no one calls you JBeans?!  I call you JBeans!"
;; -- Wilbur

;; Original Author: Mark Tran <mark.tran@gmail.com>
;; URL: http://github.com/marktran/color-theme-ujelly
;; Package-Version: 20150807.2136
;; Version: 1.1.14

;; Inspired by jellybeans: http://www.vim.org/scripts/script.php?script_id=2555.
(deftheme jbeans "The jbeans color theme")

(let ((class '((class color) (min-colors 89)))
      (jbeans-fg "#ffffff")
      (jbeans-bg "#000000")
      (jbeans-blue-0 "#8fbfdc")
      (jbeans-green-0 "#99ad6a")
      (jbeans-green-1 "#447799")
      (jbeans-green-2 "#a8ff60")
      (jbeans-grey-0 "#888888")
      (jbeans-grey-1 "#7f7f7f")
      (jbeans-grey-2 "#151515")
      (jbeans-grey-3 "#1c1c1c")
      (jbeans-grey-4 "#363636")
      (jbeans-grey-5 "#444444")
      (jbeans-orange-0 "#ffb964")
      (jbeans-purple-0 "#8197bf")
      (jbeans-purple-1 "#474e90")
      (jbeans-purple-2 "#cd00cd")
      (jbeans-purple-3 "#540063")
      (jbeans-purple-4 "#a40073")
      (jbeans-red-0 "#cf6a4c")
      (jbeans-red-1 "#dd0093")
      (jbeans-red-2 "#de5577")
      (jbeans-red-3 "#ff73fd")
      (jbeans-yellow-0 "#fad07a")
      (jbeans-yellow-1 "#ffff00"))

      (custom-theme-set-faces
       'jbeans
       `(default ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(alchemist-test--failed-face ((,class (:foreground ,jbeans-red-0))))
       `(alchemist-test--success-face ((,class (:foreground ,jbeans-green-0))))
       `(company-preview-common ((,class (:foreground nil :background ,jbeans-purple-1))))
       `(company-scrollbar-bg ((,class (:background ,jbeans-grey-2))))
       `(company-scrollbar-fg ((,class (:background ,jbeans-grey-0))))
       `(company-tooltip ((,class (:foreground ,jbeans-fg :background ,jbeans-grey-2))))
       `(company-tooltip-common ((,class (:foreground ,jbeans-red-0 :background ,jbeans-grey-2))))
       `(company-tooltip-common-selection ((,class (:foreground ,jbeans-red-0 :background ,jbeans-purple-1))))
       `(company-tooltip-selection ((,class (:background ,jbeans-purple-1))))
       `(compilation-error ((,class (:foreground ,jbeans-red-0))))
       `(compilation-info ((,class (:foreground ,jbeans-yellow-0))))
       `(compilation-line-number ((,class (:foreground ,jbeans-grey-0))))
       `(compilation-mode-line-exit ((,class (:foreground ,jbeans-green-0))))
       `(compilation-mode-line-fail ((,class (:foreground ,jbeans-red-0))))
       `(compilation-mode-line-run ((,class (:foreground ,jbeans-yellow-0))))
       `(diredp-date-time ((,class (:foreground ,jbeans-fg))))
       `(diredp-deletion ((,class (:foreground ,jbeans-red-0 :background ,jbeans-bg))))
       `(diredp-dir-heading ((,class (:foreground ,jbeans-yellow-0 :background ,jbeans-bg))))
       `(diredp-dir-priv ((,class (:foreground ,jbeans-green-2 :background ,jbeans-bg))))
       `(diredp-exec-priv ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(diredp-file-name ((,class (:foreground ,jbeans-fg))))
       `(diredp-file-suffix ((,class (:foreground ,jbeans-fg))))
       `(diredp-link-priv ((,class (:foreground ,jbeans-fg))))
       `(diredp-number ((,class (:foreground ,jbeans-fg))))
       `(diredp-no-priv ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(diredp-rare-priv ((,class (:foreground ,jbeans-red-0 :background ,jbeans-bg))))
       `(diredp-read-priv ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(diredp-symlink ((,class (:foreground ,jbeans-red-3))))
       `(diredp-write-priv ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(emmet-preview-output ((,class (:background ,jbeans-purple-1))))
       `(elixir-atom-face ((,class (:foreground ,jbeans-blue-0))))
       `(erc-notice-face ((,class (:foreground ,jbeans-yellow-0))))
       `(erc-prompt-face ((,class (:foreground ,jbeans-fg))))
       `(erc-timestamp-face ((,class (:foreground ,jbeans-purple-0))))
       `(eshell-prompt ((,class (:foreground ,jbeans-red-0))))
       `(eshell-ls-directory ((,class (:weight normal :foreground ,jbeans-green-2))))
       `(eshell-ls-executable ((,class (:weight normal :foreground ,jbeans-red-0))))
       `(eshell-ls-product ((,class (:foreground ,jbeans-fg))))
       `(eshell-ls-symlink ((,class (:weight normal :foreground ,jbeans-purple-2))))
       `(font-lock-builtin-face ((,class (:foreground ,jbeans-blue-0))))
       `(font-lock-comment-face ((,class (:slant italic :foreground ,jbeans-grey-0))))
       `(font-lock-constant-face ((,class (:foreground ,jbeans-green-1))))
       `(font-lock-doc-face ((,class (:foreground ,jbeans-green-0))))
       `(font-lock-function-name-face ((,class (:foreground ,jbeans-yellow-0))))
       `(font-lock-keyword-face ((,class (:foreground ,jbeans-purple-0))))
       `(font-lock-preprocessor-face ((,class (:foreground ,jbeans-fg))))
       `(font-lock-string-face ((,class (:foreground ,jbeans-green-0))))
       `(font-lock-type-face ((,class (:foreground ,jbeans-orange-0))))
       `(font-lock-variable-name-face ((,class (:foreground ,jbeans-red-0))))
       `(font-lock-warning-face ((,class (:foreground ,jbeans-red-1))))
       `(font-lock-regexp-grouping-construct ((t (:foreground ,jbeans-yellow-0 :bold t))))
       `(font-lock-regexp-grouping-backslash ((t (:foreground ,jbeans-red-0 :bold t))))
       `(fringe ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(git-commit-comment-file ((,class (:foreground ,jbeans-fg))))
       `(git-commit-comment-heading ((,class (:foreground ,jbeans-yellow-0))))
       `(git-commit-summary ((,class (:foreground ,jbeans-fg))))
       `(header-line ((,class (:foreground ,jbeans-fg))))
       `(helm-buffer-file ((,class (:foreground ,jbeans-fg))))
       `(helm-buffer-process ((,class (:foreground ,jbeans-yellow-0))))
       `(helm-buffer-size ((,class (:foreground ,jbeans-fg))))
       `(helm-candidate-number ((,class (:foreground ,jbeans-fg :background ,jbeans-bg))))
       `(helm-ff-directory ((,class (:background ,jbeans-bg))))
       `(helm-ff-file ((,class (:foreground ,jbeans-fg))))
       `(helm-grep-lineno ((,class (:foreground ,jbeans-fg))))
       `(helm-match ((,class (:foreground ,jbeans-red-1 :background ,jbeans-bg))))
       `(helm-moccur-buffer ((,class (:foreground ,jbeans-yellow-0))))
       `(helm-selection ((,class (:background ,jbeans-purple-1))))
       `(helm-source-header ((,class (:foreground ,jbeans-yellow-0 :background ,jbeans-grey-3))))
       `(helm-swoop-target-line-face ((,class (:foreground ,jbeans-fg :background ,jbeans-grey-4))))
       `(helm-swoop-target-word-face ((,class (:foreground ,jbeans-red-1))))
       `(hl-line ((,class (:background "#222222"))))
       `(isearch ((,class (:foreground ,jbeans-fg :background ,jbeans-red-1))))
       `(isearch-fail ((,class (:background ,jbeans-red-1))))
       `(ido-first-match ((,class (:foreground ,jbeans-yellow-0))))
       `(ido-only-match ((,class (:foreground ,jbeans-green-0))))
       `(ido-subdir ((,class (:foreground ,jbeans-fg))))
       `(ido-virtual ((,class (:foreground ,jbeans-purple-0))))
       `(lazy-highlight ((,class (:foreground ,jbeans-red-1 :background nil))))
       `(linum ((,class (:slant italic :foreground ,jbeans-grey-4))))
       `(magit-blame-heading ((,class (:foreground ,jbeans-grey-1 :background ,jbeans-grey-2))))
       `(magit-branch-local ((,class (:foreground ,jbeans-green-2))))
       `(magit-branch-remote ((,class (:foreground ,jbeans-green-2))))
       `(magit-section-heading ((,class (:foreground ,jbeans-yellow-0 :background ,jbeans-grey-2))))
       `(match ((,class (:background ,jbeans-red-1))))
       `(minibuffer-prompt ((,class (:foreground ,jbeans-fg))))
       `(mode-line ((,class (:foreground ,jbeans-fg :background nil))))
       `(mode-line-inactive ((,class (:foreground ,jbeans-grey-4 :background nil))))
       `(org-checkbox ((,class (:foreground ,jbeans-green-0))))
       `(org-date ((,class (:foreground ,jbeans-purple-0))))
       `(org-done ((,class (:foreground ,jbeans-green-0))))
       `(org-level-1 ((,class (:foreground ,jbeans-red-2))))
       `(org-level-2 ((,class (:foreground ,jbeans-red-0))))
       `(org-level-3 ((,class (:foreground ,jbeans-red-0))))
       `(org-link ((,class (:foreground ,jbeans-blue-0))))
       `(org-special-keyword ((,class (:foreground ,jbeans-purple-0))))
       `(org-todo ((,class (:foreground ,jbeans-yellow-0))))
       `(region ((,class (:background ,jbeans-purple-1))))
       `(shm-current-face ((,class (:background ,jbeans-grey-4))))
       `(shm-quarantine-face ((,class (:background ,jbeans-red-1))))
       `(smerge-markers ((,class (:foreground ,jbeans-yellow-0 :background ,jbeans-grey-2))))
       `(smerge-refined-change ((,class (:foreground ,jbeans-green-0))))
       `(sp-pair-overlay-face ((,class (:background ,jbeans-grey-4))))
       `(sp-show-pair-match-face ((,class (:background ,jbeans-grey-5))))
       `(trailing-whitespace ((,class (:background ,jbeans-red-1))))
       `(web-mode-builtin-face ((,class (:foreground ,jbeans-blue-0))))
       `(web-mode-html-attr-name-face ((,class (:foreground ,jbeans-purple-0))))
       `(web-mode-html-tag-face ((,class (:foreground ,jbeans-fg))))
       `(web-mode-symbol-face ((,class (:foreground ,jbeans-green-1))))
       `(whitespace-trailing ((,class (:background ,jbeans-red-1))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'jbeans)

;;; jbeans-theme.el ends here
